"""Small HUD icons shown over residents."""

import pygame

from graphics.icons import ICON_SIZE, icon_path
from tools.art.grid import paint

LEGEND = {
    "o": "ink", "p": "paper", "k": "ink", "e": "ember", "y": "lamp", "g": "glow", "m": "mist", "t": "teal", "d": "dust", "h": "copper", "b": "blood", "l": "lichen",
}

ICONS = {
    "chat": [
        ".oooooo.",
        "oppppppo",
        "opkkkkpo",
        "oppppppo",
        "opkkkppo",
        ".oooooo.",
        "..oo....",
        "..o.....",
    ],
    "argument": [
        ".oooooo.",
        "oeeeeeeo",
        "oekeekeo",
        "oeekkeeo",
        "oekeekeo",
        ".oooooo.",
        "..oo....",
        "..o.....",
    ],
    "alert": [
        "..oooo..",
        ".oyyyyo.",
        "oyykkyyo",
        "oyykkyyo",
        "oyykkyyo",
        "oyyyyyyo",
        ".oykkyo.",
        "..oooo..",
    ],
    "selected": [
        "........",
        "oooooooo",
        "oggggggo",
        ".oggggo.",
        "..oggo..",
        "...oo...",
        "........",
        "........",
    ],
    "work": [
        "..oooo..",
        ".oddddo.",
        ".oddddo.",
        "..ohho..",
        "..ohho..",
        "..ohho..",
        "..ohho..",
        "...oo...",
    ],
    "hurt": [
        ".oooooo.",
        "oppbbppo",
        "oppbbppo",
        "obbbbbbo",
        "obbbbbbo",
        "oppbbppo",
        "oppbbppo",
        ".oooooo.",
    ],
    "heart": [
        ".oo..oo.",
        "obboobbo",
        "obbbbbbo",
        "obbbbbbo",
        ".obbbbo.",
        "..obbo..",
        "...oo...",
        "........",
    ],
    "friend": [
        "...oo...",
        "..oyyo..",
        "oooyyooo",
        "oyyyyyyo",
        ".oyyyyo.",
        ".oyooyo.",
        "oyo..oyo",
        "oo....oo",
    ],
    "sun": [
        "y..yy..y",
        "..oooo..",
        ".oyyyyo.",
        "yoyggyoy",
        "yoyggyoy",
        ".oyyyyo.",
        "..oooo..",
        "y..yy..y",
    ],
    "moon": [
        "..oooo..",
        ".ommmo..",
        "ommmo...",
        "ommo....",
        "ommo....",
        "ommmo...",
        ".ommmo..",
        "..oooo..",
    ],
    "people": [
        "..oooo..",
        ".oppppo.",
        ".oppppo.",
        "..oooo..",
        ".oooooo.",
        "oppppppo",
        "oppppppo",
        "oooooooo",
    ],
    "food": [
        "....ol..",
        "...ol...",
        ".oobboo.",
        "obbbbbbo",
        "obbbbbbo",
        "obbbbbbo",
        ".obbbbo.",
        "..oooo..",
    ],
    "water": [
        "...oo...",
        "..ommo..",
        ".ommmo..",
        "ommmmmo.",
        "ommtmmo.",
        ".ommmmo.",
        "..oooo..",
        "........",
    ],
    "energy": [
        "..oyyo..",
        ".oyyyyo.",
        "...yy...",
        "..oyyo..",
        ".oyy....",
        "oyyyyyo.",
        "..yy....",
        ".oo.....",
    ],
    "scrap": [
        "oooooooo",
        "ohhhhhho",
        "ohdhhdho",
        "ohhddhho",
        "ohhddhho",
        "ohdhhdho",
        "ohhhhhho",
        "oooooooo",
    ],
    "eat": [
        "k.k.k..k",
        "k.k.k.kk",
        "k.k.k.kk",
        ".kkk..kk",
        "..k...k.",
        "..k...k.",
        "..k...k.",
        "..k...k.",
    ],
    "log": [
        ".oooooo.",
        "oppppppo",
        "opkkkkpo",
        "oppppppo",
        "opkkkkpo",
        "oppppppo",
        "opkkpppo",
        ".oooooo.",
    ],
    "map": [
        "oo.oo.oo",
        "oyoyyoyo",
        "oyoyyoyo",
        "oyoyyoyo",
        "oyoyyoyo",
        "oyoyyoyo",
        "oyoyyoyo",
        "oo.oo.oo",
    ],
    "brush": [
        "......oo",
        ".....oho",
        "....oho.",
        "...oho..",
        "..odo...",
        ".oyo....",
        "oyo.....",
        "oo......",
    ],
    "voice": [
        ".oooo...",
        "oppppo.o",
        "opkkpo.o",
        "oppppo.o",
        ".oppo..o",
        ".opo..o.",
        ".oo.....",
        "........",
    ],
    "sleep": [
        "....mmmm",
        "......m.",
        ".....m..",
        "....mmmm",
        "mmm.....",
        ".m......",
        "mmm.....",
        "........",
    ],
}


def build() -> dict[str, pygame.Surface]:
    art = {icon_path(name): paint(rows, LEGEND) for name, rows in ICONS.items()}
    for path, surface in art.items():
        if surface.get_size() != ICON_SIZE:
            raise ValueError(f"{path} is {surface.get_size()}, expected {ICON_SIZE}")
    return art
