"""Small HUD icons shown over residents."""

import pygame

from graphics.icons import ICON_SIZE, icon_path
from tools.art.grid import paint

LEGEND = {
    "o": "ink", "p": "paper", "k": "ink", "e": "ember", "y": "lamp", "g": "glow", "m": "mist", "t": "teal", "d": "dust", "h": "copper", "b": "blood", "l": "lichen",
}

ICONS = {
    "chat": [
        ".oooooo.",
        "oppppppo",
        "opkkkkpo",
        "oppppppo",
        "opkkkppo",
        ".oooooo.",
        "..oo....",
        "..o.....",
    ],
    "argument": [
        ".oooooo.",
        "oeeeeeeo",
        "oekeekeo",
        "oeekkeeo",
        "oekeekeo",
        ".oooooo.",
        "..oo....",
        "..o.....",
    ],
    "alert": [
        "..oooo..",
        ".oyyyyo.",
        "oyykkyyo",
        "oyykkyyo",
        "oyykkyyo",
        "oyyyyyyo",
        ".oykkyo.",
        "..oooo..",
    ],
    "selected": [
        "........",
        "oooooooo",
        "oggggggo",
        ".oggggo.",
        "..oggo..",
        "...oo...",
        "........",
        "........",
    ],
    "work": [
        "..oooo..",
        ".oddddo.",
        ".oddddo.",
        "..ohho..",
        "..ohho..",
        "..ohho..",
        "..ohho..",
        "...oo...",
    ],
    "hurt": [
        ".oooooo.",
        "oppbbppo",
        "oppbbppo",
        "obbbbbbo",
        "obbbbbbo",
        "oppbbppo",
        "oppbbppo",
        ".oooooo.",
    ],
    "heart": [
        ".oo..oo.",
        "obboobbo",
        "obbbbbbo",
        "obbbbbbo",
        ".obbbbo.",
        "..obbo..",
        "...oo...",
        "........",
    ],
    "friend": [
        "...oo...",
        "..oyyo..",
        "oooyyooo",
        "oyyyyyyo",
        ".oyyyyo.",
        ".oyooyo.",
        "oyo..oyo",
        "oo....oo",
    ],
    "sun": [
        "y..yy..y",
        "..oooo..",
        ".oyyyyo.",
        "yoyggyoy",
        "yoyggyoy",
        ".oyyyyo.",
        "..oooo..",
        "y..yy..y",
    ],
    "moon": [
        "..oooo..",
        ".ommmo..",
        "ommmo...",
        "ommo....",
        "ommo....",
        "ommmo...",
        ".ommmo..",
        "..oooo..",
    ],
    "people": [
        "..oooo..",
        ".oppppo.",
        ".oppppo.",
        "..oooo..",
        ".oooooo.",
        "oppppppo",
        "oppppppo",
        "oooooooo",
    ],
    "food": [
        "....ol..",
        "...ol...",
        ".oobboo.",
        "obbbbbbo",
        "obbbbbbo",
        "obbbbbbo",
        ".obbbbo.",
        "..oooo..",
    ],
    "water": [
        "...oo...",
        "..ommo..",
        ".ommmo..",
        "ommmmmo.",
        "ommtmmo.",
        ".ommmmo.",
        "..oooo..",
        "........",
    ],
    "energy": [
        "..oyyo..",
        ".oyyyyo.",
        "...yy...",
        "..oyyo..",
        ".oyy....",
        "oyyyyyo.",
        "..yy....",
        ".oo.....",
    ],
    "medicine": [
        "..oooo..",
        ".oppppo.",
        "oppbbppo",
        "opbbbbpo",
        "opbbbbpo",
        "oppbbppo",
        ".oppppo.",
        "..oooo..",
    ],
    "scrap": [
        "oooooooo",
        "ohhhhhho",
        "ohdhhdho",
        "ohhddhho",
        "ohhddhho",
        "ohdhhdho",
        "ohhhhhho",
        "oooooooo",
    ],
    "study": [
        ".oo..oo.",
        "oppooppo",
        "opkookpo",
        "oppooppo",
        "opkookpo",
        "oppooppo",
        ".oooooo.",
        "........",
    ],
    "eat": [
        "k.k.k..k",
        "k.k.k.kk",
        "k.k.k.kk",
        ".kkk..kk",
        "..k...k.",
        "..k...k.",
        "..k...k.",
        "..k...k.",
    ],
    "log": [
        ".oooooo.",
        "oppppppo",
        "opkkkkpo",
        "oppppppo",
        "opkkkkpo",
        "oppppppo",
        "opkkpppo",
        ".oooooo.",
    ],
    "map": [
        "oo.oo.oo",
        "oyoyyoyo",
        "oyoyyoyo",
        "oyoyyoyo",
        "oyoyyoyo",
        "oyoyyoyo",
        "oyoyyoyo",
        "oo.oo.oo",
    ],
    "brush": [
        "......oo",
        ".....oho",
        "....oho.",
        "...oho..",
        "..odo...",
        ".oyo....",
        "oyo.....",
        "oo......",
    ],
    "voice": [
        ".oooo...",
        "oppppo.o",
        "opkkpo.o",
        "oppppo.o",
        ".oppo..o",
        ".opo..o.",
        ".oo.....",
        "........",
    ],
    # How a thing was taken: to their liking, or not at all. And an eye, for something learned of someone.
    "relish": [
        "........",
        ".bb..bb.",
        "bbbbbbbb",
        "bbbbbbbb",
        ".bbbbbb.",
        "..bbbb..",
        "...bb...",
        "........",
    ],
    "disgust": [
        "........",
        ".kk..kk.",
        "..kkkk..",
        "...kk...",
        "..kkkk..",
        ".kk..kk.",
        "........",
        "........",
    ],
    "insight": [
        "........",
        "..kkkk..",
        ".k.tt.k.",
        "k.tkkt.k",
        ".k.tt.k.",
        "..kkkk..",
        "........",
        "........",
    ],
    # What the settlement counts in, where it counts in coin.
    "coin": [
        "..oooo..",
        ".oyyyyo.",
        "oyygyyyo",
        "oygyyyyo",
        "oyyyyyyo",
        "oyyyyhyo",
        ".oyyyyo.",
        "..oooo..",
    ],
    # How something was taken: swallowed, sniffed, injected or smoked. And how whoever is under it looks.
    "swallow": [
        "...oo...",
        "...oo...",
        "..oppo..",
        ".ollllo.",
        ".ollllo.",
        ".ollllo.",
        ".ollllo.",
        "..oooo..",
    ],
    "sniff": [
        "......ko",
        ".....ko.",
        "....ko..",
        "...ko...",
        "..ko....",
        "........",
        "pppppppp",
        "........",
    ],
    "inject": [
        "......oo",
        ".....omo",
        "....omo.",
        "...omo..",
        ".oomo...",
        "..oo....",
        ".o.o....",
        "o.......",
    ],
    "smoke": [
        "..m.....",
        "...m....",
        "..m.....",
        "...m....",
        "........",
        "oooooooo",
        "oppppeeo",
        "oooooooo",
    ],
    "dizzy": [
        "..kkkk..",
        ".k....k.",
        "k..kk..k",
        "k.k..k.k",
        "k.k.kk.k",
        "k.k....k",
        ".k.kkkk.",
        "..k.....",
    ],
    # A year more, and two who marry.
    "birthday": [
        "...ee...",
        "...yy...",
        "...pp...",
        ".oooooo.",
        "obbbbbbo",
        "oppppppo",
        "obbbbbbo",
        "oooooooo",
    ],
    "rings": [
        "........",
        ".oo..oo.",
        "oyyooyyo",
        "oy.yy.yo",
        "oy.yy.yo",
        "oyyooyyo",
        ".oo..oo.",
        "........",
    ],
    "sleep": [
        "....mmmm",
        "......m.",
        ".....m..",
        "....mmmm",
        "mmm.....",
        ".m......",
        "mmm.....",
        "........",
    ],
    "push": [
        "...o....",
        "..oeo...",
        "..oeeo..",
        ".oeyeo..",
        ".oeyyeo.",
        "oeyyyeo.",
        "oeyyyeo.",
        ".ooooo..",
    ],
    "train": [
        "........",
        ".o....o.",
        "oeo..oeo",
        "oemmmmeo",
        "oemmmmeo",
        "oeo..oeo",
        ".o....o.",
        "........",
    ],
    # Over whoever wants a word of the player (P62).
    "ask": [
        "...ee...",
        "..eeee..",
        "..eeee..",
        "...ee...",
        "...ee...",
        "........",
        "...ee...",
        "...ee...",
    ],
    # Over whoever wants something for themselves (P63): what is on their mind.
    "wish": [
        ".ooooo..",
        "opppppo.",
        "oppyppo.",
        "opyyypo.",
        "oppyppo.",
        ".ooooo..",
        "....oo..",
        "......o.",
    ],
    "mood": [
        "..oooo..",
        ".oyyyyo.",
        "oykyykyo",
        "oyyyyyyo",
        "oykyykyo",
        "oyykkyyo",
        ".oyyyyo.",
        "..oooo..",
    ],
}


def build() -> dict[str, pygame.Surface]:
    art = {icon_path(name): paint(rows, LEGEND) for name, rows in ICONS.items()}
    for path, surface in art.items():
        if surface.get_size() != ICON_SIZE:
            raise ValueError(f"{path} is {surface.get_size()}, expected {ICON_SIZE}")
    return art
